### PR TITLE
fix null byte array typing

### LINKED ISSUE #1038: Null byte[] arguments become ARRAY type
I just ran into an issue while trying to use nullable binary types, with byte[] fields on a bound bean object. Derby was spewing errors about unsupported ARRAY types.

I did a little digging and it looks like the problem occurs in SqlArrayArgumentFactory, where the null byte[] is assumed to be an ARRAY type:
https://github.com/jdbi/jdbi/blob/90af5ec3ac74e05919d7e90eb87ce2af8e7ba9ed/core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java#L50-L52

However, if the value is not null, it will move on to the BuiltInArgumentFactory and use the correct type.

### PR DESCRIPTION
**Pull request by TheRealMarnes**
fixes #1038

### CODE REVIEW

**Comment by TheRealMarnes** [comment]
Included is a bit of general cleanup in the involved classes, and a refactor of the factory itself to split the main method into its 2 parts that were lobbed together, for clarity.

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java [hunk 1]
```diff
@@ -18,34 +18,27 @@
...
-    @SuppressWarnings("unchecked")
     SqlArrayArgument(SqlArrayType<T> arrayType, Object newArray) {
         this.typeName = arrayType.getTypeName();
 
-        List<Object> elements = new ArrayList<>(
-                newArray.getClass().isArray() ? Array.getLength(newArray) : 10);
-        IterableLike.of(newArray).forEachRemaining(
-                e -> elements.add(arrayType.convertArrayElement((T) e)));
+        List<Object> elements = new ArrayList<>(newArray.getClass().isArray() ? Array.getLength(newArray) : 10);
+        IterableLike.of(newArray).forEachRemaining(e -> {
```
Comment (stevenschlansker) [inline core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java]: What's going on in this refactoring?  It looks the same but it's way wordier now.  This doesn't seem like an improvement to me unless I'm missing something.

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java [hunk 2]
```diff
@@ -41,27 +40,41 @@
...
-            return Optional.of(new NullArgument(Types.ARRAY));
+        if (rawType.isArray()) {
+            if (value == null) {
+                return Optional.of(new NullArgument(Types.ARRAY));
+            }
+
+            return config.get(SqlArrayTypes.class)
+                .findFor(rawType.getComponentType())
+                .map(arrayType -> new SqlArrayArgument<>(arrayType, value));
         }
```
Comment (stevenschlansker) [inline core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java]: I'm not sure I see the improvement in this refactoring either.  It also ends up being significantly longer.  What was wrong with the original code?

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java (hunk 1 above)
Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java]: If you open the old code, not being familiar with it, it takes some serious reading to figure out. The lookup variable just obscured the process. The whole method top to bottom just goes "this is either an array or a list, we're gonna cast it to whichever it is, and call 2 different flows to finish up depending on which it is". For all intents and purposes the method was just 2 functionally distinct methods clobbered together to save on lines of text, and not really structured to express its binary nature either.

I just factored the 2 methods apart and sort of normalized them. The fact that they look very different now is a clear sign they shouldn't have been writting as one whole. They happen to share a few variables and the null part, but that's all they share.

It's all about clarifying intent, making expression match function.

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java]: oh, and IDE support becomes pretty crap too when a variable is inferred to be "either this or that, who knows" :p

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java]: Oh, this part. Reducing the scope of the SuppressWarnings

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java (hunk 2 above)
Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java]: First 2 replies on the other remark were meant for this one

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java]: If you open the old code, not being familiar with it, it takes some serious reading to figure out. The lookup variable just obscured the process. The whole method top to bottom just goes "this is either an array or a list, we're gonna cast it to whichever it is, and call 2 different flows to finish up depending on which it is". For all intents and purposes the method was just 2 functionally distinct methods clobbered together to save on lines of text, and not really structured to express its binary nature either.

I just factored the 2 methods apart and sort of normalized them. The fact that they look very different now compared to each other is a clear sign they shouldn't have been written as one whole. They happen to share a few variables and the null part, but that's all they share.

It's all about clarifying intent, making expression match function.

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java]: oh, and IDE support becomes pretty crap too when a variable is inferred to be "either this or that, who knows" :p

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java (hunk 1 above)
Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java]: It turned two lines into five lines, that sure seems wordier to me.  You even extracted out a new variable `cast` that is totally useless.  This PR would have been a slam dunk if it just had the relevant fix at hand...

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java (hunk 2 above)
Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java]: I think the intent is a lot less clear now.  Before, it read nicely, "If the type doesn't match, exit.  If it's null, bind null.  Otherwise look up the element binder.  Then, depending on whether it's an array or collection, find the element type and bind it.  One less controversial improvement might be to move the "how do I find the element type" bit to `IterableLike` which would remove the final branch from the code.

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java (hunk 1 above)
Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgument.java]: ?? I only _added_ 1 line of minimal code, by extracting the cast to keep the scope of the SuppressWarnings to a minimum. The only other addition is a pair of brackets because multiline lambda. I really don't see how it's wordier. It's not more code. I literally just moved the suppresswarnings and extracted a variable for good practice.

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java (hunk 2 above)
Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java]: I'll see if I can rewrite it to more of a golden middle way. I agree it is _larger_, but I generally find surface area much less of a mental burden/complexity than number of operations per method, ambiguity or sub-methods (the schroedinger variable being "one of two" types at the same time that require different handling every step of the way), and back-and-forth branching between 2 different processes that are conjoined at the hip for sharing a few lines of elementary code.

But my vote for the refactor bit (separate commit) is a soft vote, if your objection tends toward hard I can just stop caring about it, rewind the commit, and we'll move on.

File: core/src/main/java/org/jdbi/v3/core/internal/IterableLike.java [hunk 3]
```diff
@@ -68,6 +72,16 @@ public static boolean isIterable(Object maybeIterable) {
         return Arrays.asList((Object[]) iterable).iterator();
     }
 
+    /**
+     * Given an iterable object (which may be a iterator, iterable, primitive
+     * or reference array), return a {@link Stream} over its (possibly boxed) elements.
+     *
+     * @return an iterator of the given array's elements
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/internal/IterableLike.java]: s/iterator/stream/

File: core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java [hunk 4]
```diff
@@ -41,27 +39,24 @@
...
-            Class<?> elementType = erasedType.getComponentType();
-            return lookup.apply(elementType)
-                    .map(arrayType -> new SqlArrayArgument<>(arrayType, value));
-        }
-
-        return GenericTypes.findGenericParameter(type, Collection.class)
-                .flatMap(lookup)
+        if (rawClass.isArray()) {
+            return config.get(SqlArrayTypes.class)
+                .findFor(rawClass.getComponentType())
```
Comment (stevenschlansker) [inline core/src/main/java/org/jdbi/v3/core/array/SqlArrayArgumentFactory.java]: It still irks me slightly that the `findFor` bit is duplicated here.  I'll make one quick fixup then it's good to go.

**Comment by stevenschlansker** [comment]
I pulled out the 'find element type' logic into `IterableLike`, since it already has related functionality.  I think the result is a lot clearer, and as a bonus, we now recognize `Iterator<T> `in addition to `Iterable<T>`.  Hopefully you like the change: https://github.com/jdbi/jdbi/pull/1386/commits/ecfe3c86ce3b3ed3d6da54abd1bf0550a15e0785

**Comment by TheRealMarnes** [comment]
Wholeheartedly agreed, that's a neat change :+1:

**Comment by stevenschlansker** [comment]
Oops, I broke it.  One more try...
