### PR TITLE
Do sanity checks on SQL object attach: non-default method with no ann…

### LINKED ISSUE #477: SQLObject should throw exception when a non-abstract SQL method has a SQL method annotation.
Since a SQL method annotation implies a specific implementation, it is an error to annotate a concrete (default) method with a SQL method annotation e.g. `@SqlUpdate`

### PR DESCRIPTION
**Pull request by qualidafial**
…otation, default method with sql method annotations should both throw exceptions

Fixes #477, #488

### CODE REVIEW

File: sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java [hunk 1]
```diff
@@ -145,13 +144,25 @@ private Handler buildBaseHandler(Class<?> sqlObjectType, Method method) {
                             method.getName(),
                             sqlMethodAnnotations));
         }
+        if (method.isDefault()) {
+            if (!sqlMethodAnnotations.isEmpty()) {
+                throw new IllegalStateException(String.format(
+                        "Method %s.%s has mutually exclusive default implementation and a SQL method annotation (must be one or the other)",
```
Comment (qualidafial) [inline sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java]: Hmm, might be good to mention the class of the offending annotation.

File: sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java [hunk 2]
```diff
@@ -133,10 +131,10 @@ private Handler buildMethodHandler(Class<?> sqlObjectType, Method method) {
     }
 
     private Handler buildBaseHandler(Class<?> sqlObjectType, Method method) {
-        Set<Class<?>> sqlMethodAnnotations = Stream.of(method.getAnnotations())
+        List<Class<?>> sqlMethodAnnotations = Stream.of(method.getAnnotations())
```
Comment (arteam) [inline sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java]: Could you, please, elaborate why we need here a list rather than a set?

File: sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestSqlObject.java [hunk 3]
```diff
@@ -65,15 +66,16 @@ public void testPassThroughMethod() throws Exception
         assertThat(c, equalTo(new Something(3, "Cora")));
     }
 
-    @Test
+    @Test(expected = AbstractMethodError.class)
```
Comment (arteam) [inline sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestSqlObject.java]: I think it would be great to verify the message of the exception as well.

File: sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java (hunk 2 above)
Comment (qualidafial) [inline sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java]: Aesthetic only. `list.get(0)` feels slightly less gross than `set.iterator().next()` ¯\\\_(ツ)\_/¯

File: sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java [hunk 4]
```diff
@@ -145,13 +143,27 @@ private Handler buildBaseHandler(Class<?> sqlObjectType, Method method) {
...
+            return new DefaultMethodHandler();
+        }
 
         return sqlMethodAnnotations.stream()
                 .map(type -> type.getAnnotation(SqlMethodAnnotation.class))
                 .map(a -> buildFactory(a.value()))
                 .map(factory -> factory.buildHandler(sqlObjectType, method))
                 .findFirst()
-                .orElseGet(PassThroughHandler::new);
+                .orElseThrow(() -> new AbstractMethodError(String.format(
```
Comment (stevenschlansker) [inline sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java]: It feels weird for one error path to throw `IllegalStateException` and another to throw `AbstractMethodError`.  I get why, and I can't think of anything better off the top of my head, but it caught my eye.

Comment (qualidafial) [inline sqlobject/src/main/java/org/jdbi/v3/sqlobject/SqlObjectFactory.java]: We could throw a different exception here. The two cases are opposite sides of the same coin, so I could see `IllegalStateException` being fine here.
