### PR TITLE
Fix handle close + transaction handling errors

### LINKED ISSUE #1405: Built-in transaction handler causes ClassCastException when an Error is thrown
The transaction handler causes a `ClassCastException` if an `Error` is thrown while executing the transaction.

If , for example, the template engine throws an error like so:

```java
jdbi.setTemplateEngine((sql, ctx) -> {
  throw new Error();
});
```

the error isn't propagated but causes this exception instead:

```
java.lang.ClassCastException: java.lang.Error cannot be cast to java.lang.Exception
	at org.jdbi.v3.core.transaction.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:145)
	at org.jdbi.v3.core.transaction.SerializableTransactionRunner.inTransaction(SerializableTransactionRunner.java:54)
	at org.jdbi.v3.core.Handle.inTransaction(Handle.java:393)
	at org.jdbi.v3.core.Jdbi.lambda$inTransaction$5(Jdbi.java:353)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:318)
	at org.jdbi.v3.core.Jdbi.inTransaction(Jdbi.java:353)
```

### LINKED ISSUE #1406: Handle.close() might cause Connection leaks if the autocommit state of the underlying connection cannot be determined
We're using a statement timeout in our JDBC connection String. On long running statements, this causes the JDBC driver or the database to close the connection which is used by a JDBI Handle.  When JDBI tries to close the Handle, an Exception is thrown in the call to isInTransaction(). The control flow of Handle.close() is interrupted by the Exception thrown in isInTransaction(), which means the close() Method of the Connection held by the Handle is never called, causing a Connection leak that is observable with JProfiler. 

The Situation as a [Stacktrace](https://github.com/jdbi/jdbi/files/2755028/Stacktrace.txt)

Since this occurs in a Payara-Micro Appserver I'm also attaching the relevant parts of the 
[glassfish-resources.xml](https://github.com/jdbi/jdbi/files/2755051/glassfish-resources.txt)

### PR DESCRIPTION
**Pull request by stevenschlansker**
Fixes #1405 
Fixes #1406

### CODE REVIEW

File: core/src/test/java/org/jdbi/v3/core/TestHandle.java [hunk 1]
```diff
@@ -77,4 +80,61 @@ public void unknownTransactionLevelIsOk() {
...
+        final BoomHandler handler = new BoomHandler();
+        dbRule.getJdbi().setTransactionHandler(handler);
+        final Handle h = dbRule.openHandle();
+
+        assertThat(h.isClosed()).isFalse();
+
+        handler.failRollback = true;
+        assertThatThrownBy(() -> h.useTransaction(h2 -> h2.execute("insert into true")))
+            .isInstanceOf(UnableToCreateStatementException.class);
+        assertThat(h.isInTransaction()).isTrue(); // rollback failed!
```
Comment (TheRealMarnes) [inline core/src/test/java/org/jdbi/v3/core/TestHandle.java]: Comments clarifying tests should be added with `.describedAs(String)` instead of java source comments

**Comment by stevenschlansker** [comment]
@qualidafial if you have time to review this as well, I'd appreciate it, given how sensitive the code it touches is...

File: core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java [hunk 2]
```diff
@@ -135,7 +135,7 @@ public boolean isInTransaction(Handle handle) {
             if (!didTxnRollback.get()) {
                 handle.commit();
             }
-        } catch (Exception e) {
+        } catch (Exception | Error e) {
```
Comment (sarxos) [inline core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: Hi @stevenschlansker,

I think this should be `Throwable`. The `Error` case is very specific and I assume it was only provided in #1405 as an example to demonstrate the problem, but in a wild there is a bunch of `Throwable` monsters (especially in Scala) which are neither `Exception` nor `Error` but which can easily flip stack trace upside down.

Therefore, if there are no other reasons to limit a range of throwables being caught here, I think this should be changed to:

```java
} catch (Throwable t) {
```

Both `Error` and `Exception` are instances of `Throwable`, but the `Error` is **not** instance of `X extends Exception`. I guess this works only because IDE or compiler did not pick it up since generics are erased in compile time and `X extends Exception` disappears.

File: RELEASE_NOTES [hunk 3]
```diff
@@ -35,6 +35,8 @@
       from the BOM.
   - API changes
     - SQLitePlugin now has the ServiceLoader manifest it deserves for automagical installation.
+  - Improvements
+    - local transaction handler: handle Errors and ensure we rollback
```
Comment (qualidafial) [inline RELEASE_NOTES]: Needs to move to 3.7.0 section, in new RELEASE_NOTES.md file

File: core/src/main/java/org/jdbi/v3/core/Handle.java [hunk 4]
```diff
@@ -122,47 +124,59 @@ public Handle setStatementBuilder(StatementBuilder builder) {
...
         if (closed) {
             return;
         }
 
-        boolean wasInTransaction = isInTransaction()
-            && forceEndTransactions
-            && config.get().get(Handles.class).isForceEndTransactions();
+        boolean wasInTransaction = forceEndTransactions
+                && config.get().get(Handles.class).isForceEndTransactions();
+
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/Handle.java]: Why did the `isInTransaction()` part get removed?

File: core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java (hunk 2 above)
Comment (qualidafial) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: The `X extends Exception` approach is how we get exception transparency in Jdbi calls. That is, `inTransaction()` can only throw whatever checked exceptions are thrown by your lambda. That's how we got away from wrapping every exception in e.g. `DBIException` like we did in v2.

File: core/src/main/java/org/jdbi/v3/core/Handle.java [hunk 5]
```diff
@@ -122,47 +124,59 @@ public Handle setStatementBuilder(StatementBuilder builder) {
...
+        if (wasInTransaction) {
+            try {
+                wasInTransaction &= isInTransaction();
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/Handle.java]: Can we move this stuff into `isInTransaction()` instead? We could probably leave this method as is if `isInTransaction()` checked whether the connection was already closed--unless I'm missing something.

File: core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java (hunk 2 above)
Comment (qualidafial) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: From Error javadoc:

> An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch.

Since we're no longer catching `Throwable` and casting to `X`, do we actually need this change?

Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: > The X extends Exception approach is how we get exception transparency in Jdbi calls.
(although it really ought to have been `X extends Throwable`, but we didn't figure that out until too late to change it for v3)

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: Why not catch throwable instead of only the subtypes error and exception?

File: core/src/main/java/org/jdbi/v3/core/Handle.java (hunk 4 above)
Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/Handle.java]: It didn't; it's simply moved down below.  I reorganized the `A() && B && C` clause to `if (B && C) { A() }` since two of them are local booleans and `isInTransaction` potentially calls out to the remote database server or throws.

File: core/src/main/java/org/jdbi/v3/core/Handle.java (hunk 5 above)
Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/Handle.java]: I don't think so.  If we move the exception catching into `isInTransaction` we are then forced to handle the exception then and there and invent a fallback `boolean` value -- do we pretend to be in a transaction?  or not?  neither is right all the time.  so I don't think the contract of `isInTransaction` should change -- if it can't determine it, it should throw.

Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/Handle.java]: This guards against arbitrary problems -- imagine an `EOFException` while trying to query the server's transaction status -- not just concurrent closes.

File: core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java (hunk 2 above)
Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: I'm surprised `catch (Throwable e)` compiles.  The method `throws X (extends Exception)` and there are many throwables that don't match that signature... you must be right about funky erasure semantics here.

**Comment by stevenschlansker** [comment]
I rebased this PR against master and went through all the comments.  One last review?

File: core/src/main/java/org/jdbi/v3/core/Handle.java [hunk 6]
```diff
@@ -122,47 +124,57 @@ public Handle setStatementBuilder(StatementBuilder builder) {
...
             if (wasInTransaction) {
                 TransactionException txe = new TransactionException("Improper transaction handling detected: A Handle with an open "
                     + "transaction was closed. Transactions must be explicitly committed or rolled back "
                     + "before closing the Handle. "
                     + "Jdbi has rolled back this transaction automatically. "
                     + "This check may be disabled by calling getConfig(Handles.class).setForceEndTransactions(false).");
-                if (suppressed != null) {
-                    txe.addSuppressed(suppressed);
-                }
+                suppressed.forEach(txe::addSuppressed);
```
Comment (sarxos) [inline core/src/main/java/org/jdbi/v3/core/Handle.java]: This lambda code is dead because `suppressed` list is **always** empty here. This is because for non-empty `supressed` list the `if` block in 161 is executed which throws `CloseException` in 164 making this one unreachable. Therefore, the only way for this line to run is to have `suppressed` list empty, but, because it's empty the lambda within `forEach` will never run.

I suggest to unify suppression propagation in a `catch` blocks to make it simpler:

```java
try {
  closer.close()
  if (wasInTransaction && suppressed.isEmpty()) {
    throw new TransactionException("Improper ...");
  }
} catch (Throwable t) {
  CloseException ce = new CloseException("Unable to close Connection", t);
  suppressed.forEach(ce::addSuppressed);
  throw ce;
} finally {
  closed = true;
}

if (!suppressed.isEmpty()) {
  CloseException ce = new CloseException("Failed to clear transaction status on close", suppressed.remove(0));
  suppressed.forEach(ce::addSuppressed);
  throw ce;  
}
```

The above code is just to present an idea. I was writing it without IDE so it may may not compile or may be buggy or violate some dependencies or requirements in call stack which I'm not aware of.

Comment (qualidafial) [reply core/src/main/java/org/jdbi/v3/core/Handle.java]: I think @sarxos has it right. This line of code is unreachable if `suppressed` is non-empty. So this line is superfluous.

File: core/src/main/java/org/jdbi/v3/core/Handle.java [hunk 7]
```diff
@@ -122,47 +124,57 @@ public Handle setStatementBuilder(StatementBuilder builder) {
...
                 throw txe;
             }
         } catch (SQLException e) {
             CloseException ce = new CloseException("Unable to close Connection", e);
-            if (suppressed != null) {
-                ce.addSuppressed(suppressed);
-            }
+            suppressed.forEach(ce::addSuppressed);
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/Handle.java]: I believe this line is similarly unnecessary.

File: core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java [hunk 8]
```diff
@@ -135,7 +135,7 @@ public boolean isInTransaction(Handle handle) {
             if (!didTxnRollback.get()) {
                 handle.commit();
             }
-        } catch (Exception e) {
+        } catch (Throwable e) {
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: From the Throwable javadoc:

```
For the purposes of compile-time checking of exceptions, {@code
Throwable} and any subclass of {@code Throwable} that is not also a
subclass of either {@link RuntimeException} or {@link Error} are
regarded as checked exceptions.
```

So I don't understand how the compiler allows `throw e` in this context.

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: My money is on generics erasure shenanigans confusing the compiler. Report it as a bug and win 5 million bucks for finding a flaw in java?

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: Explicitly writing ` throw new Throwable();` anywhere in the method still gives a compile error...

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: Exhibit A ^^

image

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: Yeah, looks like the compiler can narrow the caught exception type on its own regardless of the declaration:
image

So it probably omits the "can't throw a Throwable here" because it knows you'll never catch a `Throwable`.

Comment (qualidafial) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: Huh. Well that's nifty.

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/transaction/LocalTransactionHandler.java]: For completeness:
image

File: core/src/main/java/org/jdbi/v3/core/Handle.java (hunk 7 above)
Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/Handle.java]: I think this one's actually needed, in case e.g. the `statementBuilder` throws and then so does `closer.close`.
