### PR TITLE
Batch insert: fix inserting constant 'null'

### LINKED ISSUE #1761: NullPointerException in SqlBatch with a constant parameter value of null
I'm trying to execute an `@SqlBatch` with a constant parameter value of `null`. This causes a `NullPointerException` in JDBI while  testing if arguments are iterable-like.

This code reproduces the issue:
```java
public interface Sql {
  // create table user (tenant_id varchar(20), name varchar(20))
  @SqlBatch("insert into user(tenant_id, name) values (:tenantId, :name);")
  void insert(String tenantId, @Bind("name") List<String> names);
}

Jdbi jdbi = Jdbi.create(connectionUrl);
jdbi.installPlugin(new SqlObjectPlugin());
jdbi.useHandle(handle -> {
  Sql sql = handle.attach(Sql.class);
  sql.insert(null, asList("foo", "bar"));
});
```

Stacktrace:
```
java.lang.NullPointerException
	at org.jdbi.v3.core.internal.IterableLike.isIterable(IterableLike.java:48)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.zipArgs(SqlBatchHandler.java:269)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.invoke(SqlBatchHandler.java:174)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.lambda$invoke$0(SqlObjectInitData.java:125)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.ConstantHandleSupplier.lambda$invokeInContext$0(ConstantHandleSupplier.java:56)
	at org.jdbi.v3.core.internal.Invocations.invokeWith(Invocations.java:44)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.call(SqlObjectInitData.java:131)
	at org.jdbi.v3.sqlobject.internal.SqlObjectInitData$1.invoke(SqlObjectInitData.java:125)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$attach$2(SqlObjectFactory.java:110)
	at com.sun.proxy.$Proxy39.insert(Unknown Source)
```

### PR DESCRIPTION
**Pull request by stevenschlansker**
Fixes #1761

### CODE REVIEW

File: sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java [hunk 1]
```diff
@@ -67,6 +67,21 @@ public void testInsertSingleIteratorNoTx() {
         assertThat(b.size()).isEqualTo(2);
     }
 
+    @Test
+    public void testBindConstantNull() {
+        UsesBatching b = handle.attach(UsesBatching.class);
```
Comment (leaumar) [inline sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java:72]: avoid single-letter variables please (aside from the meme `i` for iterations, I'd say `Handle h` at most could also be a meme in our context)

File: sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java [hunk 2]
```diff
@@ -67,6 +67,21 @@ public void testInsertSingleIteratorNoTx() {
...
+        List<Integer> ids = Arrays.asList(1, 2, 3, 4, 5);
+
+        b.withConstantValue(ids, null);
+
+        assertThat(b.size()).isEqualTo(5);
```
Comment (leaumar) [inline sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java:77]: isn't there a `hasSize`?

File: sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java (hunk 1 above)
Comment (stevenschlansker) [reply sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java:72]: Ah, this is all just clone of existing tests, with only one other change...

File: sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java (hunk 2 above)
Comment (stevenschlansker) [reply sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java:77]: This isn't a Collection, so that doesn't apply.

File: sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java (hunk 1 above)
Comment (leaumar) [reply sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestBatching.java:72]: Sounds like the improvement could be made in 2 places :)
