### PR TITLE
Fix statement leak from exceptional @GetGeneratedKeys

### LINKED ISSUE #230: Failing statements with @GetGeneratedKeys leaks cursors on Oracle
An `SqlObject` method with `@GetGeneratedKeys` that fails during execution (resulting in an `UnableToExecuteStatementException`) leaks a cursor on Oracle. After enough failures, the connection runs out of cursors, rendering it useless. Adding a call to `close` in the `catch` clause that maps `SQLException` to `UnableToExecuteStatementException` in `SQLStatement.internalExecute` fixes it, but I'm unsure of the implications of doing that.

### PR DESCRIPTION
**Pull request by stevenschlansker**
Fixes #230 
the fix is not great... but can be fixed better for JDBI3!

### CODE REVIEW

File: src/main/java/org/skife/jdbi/v2/SQLStatement.java [hunk 1]
```diff
@@ -1329,6 +1329,11 @@ private String wrapLookup(String sql)
             timingCollector.collect(elapsedTime, getContext());
         }
         catch (SQLException e) {
+            try {
+                stmt.close();
+            } catch (SQLException e1) {
+                e1.printStackTrace(); // TODO: we have nowhere to log this, and suppressed exceptions were added in Java 7...
```
Comment (qualidafial) [inline src/main/java/org/skife/jdbi/v2/SQLStatement.java]: Why not SLF4J?

**Comment by qualidafial** [comment]
One comment, then :shipit:

File: src/main/java/org/skife/jdbi/v2/SQLStatement.java (hunk 1 above)
Comment (stevenschlansker) [inline src/main/java/org/skife/jdbi/v2/SQLStatement.java]: slf4j is not a mandatory dependency, so cannot be used or you risk linking errors:

```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <optional>true</optional>
        </dependency>
```

:cry:
