### PR TITLE
Avoid SqlBatch customizer null argument

### LINKED ISSUE #1516: Custom StatementCustomizer does not work with @SqlBatch anymore
I just updated from JDBI 3.4.0 to 3.8.0 and when I use a custom StatementCustomizer on a SqlBatch (that worked on 3.4.0) it now fails with a NullPointerException

The method beforeExecution is receiving first parameter "stmt" which is null !

What did I do wrong ? Is that a bug in JDBI ?

    java.lang.NullPointerException
	at org.jdbi.v3.sqlobject.customizer.internal.ReadOnlyCheckCustomizer.beforeExecution(ReadOnlyCheckCustomizer.java:15)
	at org.jdbi.v3.core.statement.SqlStatement.lambda$beforeExecution$9(SqlStatement.java:1600)
	at org.jdbi.v3.core.statement.BaseStatement.callCustomizers(BaseStatement.java:80)
	at org.jdbi.v3.core.statement.SqlStatement.beforeExecution(SqlStatement.java:1600)
	at org.jdbi.v3.core.statement.PreparedBatch.internalBatchExecute(PreparedBatch.java:171)
	at org.jdbi.v3.core.statement.PreparedBatch.execute(PreparedBatch.java:66)
	at org.jdbi.v3.core.statement.PreparedBatch.executeAndGetModCount(PreparedBatch.java:71)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.executeBatch(SqlBatchHandler.java:310)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.access$000(SqlBatchHandler.java:46)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler$2.hasNext(SqlBatchHandler.java:206)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.invoke(SqlBatchHandler.java:232)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$18(SqlObjectFactory.java:184)
	at org.jdbi.v3.core.ConstantHandleSupplier.invokeInContext(ConstantHandleSupplier.java:52)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$19(SqlObjectFactory.java:181)
	at com.sun.proxy.$Proxy46.insertCommunityRatings(Unknown Source)
	at com.beasyness.api.service.communities.CommunityRatingDaoSpec$1$7$1.invoke(CommunityRatingDaoSpec.kt:169)

Here are the relevant parts of the code :

The usage 

    @SqlBatch("replace into communities_ratings (communityId, memberId, providerId, avgRate, isRecommended) " +
            "values (:communityId, :memberId, :providerId, :avgRate, :recommended)")
    @ReadOnlyCheck
    fun insertCommunityRatings(@BindBean communityRatings: List<CommunityRatingDbRow>)

The interface

    package org.jdbi.v3.sqlobject.customizer;
    
    import org.jdbi.v3.sqlobject.customizer.internal.ReadOnlyCheckFactory;
    
    import java.lang.annotation.ElementType;
    import java.lang.annotation.Retention;
    import java.lang.annotation.RetentionPolicy;
    import java.lang.annotation.Target;
    
    @Retention(RetentionPolicy.RUNTIME)
    @Target({ElementType.METHOD})
    @SqlStatementCustomizingAnnotation(ReadOnlyCheckFactory.class)
    public @interface ReadOnlyCheck {
    }

The implementation

    package org.jdbi.v3.sqlobject.customizer.internal;

    import org.jdbi.v3.core.statement.StatementContext;
    import org.jdbi.v3.core.statement.StatementCustomizer;

    import java.sql.PreparedStatement;
    import java.sql.SQLException;

    public class ReadOnlyCheckCustomizer implements StatementCustomizer {

        public static final String EXCEPTION = "can not perform this operation on a readonly connection";

        @Override
        public void beforeExecution(PreparedStatement stmt, StatementContext ctx) throws SQLException {
            if (stmt.getConnection().isReadOnly()) {
                throw new SQLException(EXCEPTION);
            }
        }
    }

    package org.jdbi.v3.sqlobject.customizer.internal;
    
    import org.jdbi.v3.sqlobject.customizer.SqlStatementCustomizer;
    import org.jdbi.v3.sqlobject.customizer.SqlStatementCustomizerFactory;
    
    import java.lang.annotation.Annotation;
    import java.lang.reflect.Method;
    
    public class ReadOnlyCheckFactory implements SqlStatementCustomizerFactory {
        @Override
        public SqlStatementCustomizer createForMethod(Annotation annotation, Class<?> sqlObjectType, Method method) {
            return stmt -> stmt.addCustomizer(new ReadOnlyCheckCustomizer());
        }
    }

### PR DESCRIPTION
**Pull request by TheRealMarnes**
fixes #1516 

I'm not sure what the comment on the field was all about, but git says it's from 2007 so I'm not tempted to assign too much importance to it. Did not read the class in detail though, so I'm not sure if I may have subtly violated something here or not.

### CODE REVIEW

File: core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java [hunk 1]
```diff
@@ -65,11 +65,7 @@
 public abstract class SqlStatement<This extends SqlStatement<This>> extends BaseStatement<This> {
     private final Handle handle;
     private final String sql;
-
-    /**
-     * This will be set on execution, not before
-     */
-    private PreparedStatement stmt;
+    protected PreparedStatement stmt;
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java]: Can this be package private?

**Comment by stevenschlansker** [comment]
Added release note and required license header.
