### PR TITLE
Resolve generic method parameters from SQL object superclass

### LINKED ISSUE #1473: SQLBatch issues in generic class
Hello, I just encountered a problem with SQLBatch inside a generic class.
```
@UseClasspathSqlLocator
public interface BaseDAO<T> {
    @SqlBatch
    void insertAll(@BindBean("e") Collection<T> entities);
}

public interface AirspaceDAO extends BaseDAO<Airspace> {

}
```

When trying to get jdbi implementation of the AirspaceDAO via handle.attach, I get this exception:
```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.getParameterType(SqlBatchHandler.java:158)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$eachParameterCustomizers$5(CustomizingStatementHandler.java:98)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.eachParameterCustomizers(CustomizingStatementHandler.java:99)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.lambda$parameterCustomizers$4(CustomizingStatementHandler.java:89)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.<init>(CustomizingStatementHandler.java:73)
	at org.jdbi.v3.sqlobject.statement.internal.SqlBatchHandler.<init>(SqlBatchHandler.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.buildHandler(SqlMethodHandlerFactory.java:68)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.lambda$buildHandler$2(SqlMethodHandlerFactory.java:57)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.jdbi.v3.sqlobject.SqlMethodHandlerFactory.buildHandler(SqlMethodHandlerFactory.java:58)
	at org.jdbi.v3.sqlobject.Handlers.lambda$findFor$0(Handlers.java:56)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.jdbi.v3.sqlobject.Handlers.findFor(Handlers.java:57)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.buildMethodHandler(SqlObjectFactory.java:133)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$9(SqlObjectFactory.java:125)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$methodHandlersFor$10(SqlObjectFactory.java:125)
	at java.util.Map.computeIfAbsent(Map.java:957)
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2672)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.methodHandlersFor(SqlObjectFactory.java:106)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.attach(SqlObjectFactory.java:83)
	at org.jdbi.v3.core.extension.Extensions.lambda$findFor$0(Extensions.java:70)
	at java.util.Optional.map(Optional.java:215)
	at org.jdbi.v3.core.extension.Extensions.findFor(Extensions.java:70)
	at org.jdbi.v3.core.Handle.attach(Handle.java:504)
```
However when I override the method in the descendant, it works fine.
```
public interface AirspaceDAO extends BaseDAO<Airspace> {

    @SqlBatch
    @Override
    void insertAll(@BindBean("e") Collection<Airspace> entities);
}
```
When debugging I looked into GenericTypes.findGenericParameter, and in problematic case parameterType is instance of TypeVariableImpl, but I do not know if it is helpful.
```
    public static Optional<Type> findGenericParameter(Type type, Class<?> parameterizedSupertype) {
        Type parameterType = resolveType(parameterizedSupertype.getTypeParameters()[0], type);
        return parameterType instanceof Class || parameterType instanceof ParameterizedType
                ? Optional.of(parameterType)
                : Optional.empty();
    }
```
Is this use case not supported or am I using a wrong approach? Thanks a lot for answer!

### PR DESCRIPTION
**Pull request by qualidafial**
Fixes #1473

### CODE REVIEW

File: sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestSqlObject.java [hunk 1]
```diff
@@ -88,7 +91,7 @@ public void testRedundantMethodHasDefaultImplementAndAlsoSqlMethodAnnotation() {
 
     @Test
     public void testPassThroughMethodWithDaoInAnotherPackage() {
-        SomethingDao dao = handle.attach(SomethingDao.class);
+        org.jdbi.v3.sqlobject.subpackage.SomethingDao dao = handle.attach(org.jdbi.v3.sqlobject.subpackage.SomethingDao.class);
```
Comment (qualidafial) [inline sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestSqlObject.java]: Ugh. Didn't notice this. Will rename the DAO in this test to something else

**Comment by TheRealMarnes** [comment]
> java.lang.IllegalArgumentException: Cannot find classpath resource at org/jdbi/v3/sqlobject/TestSqlObject$ExtendGenericDaoWithExplicitParameter/batchInsert.sql
	at org.jdbi.v3.sqlobject.TestSqlObject.genericSuperclassExtendedByExplicitTypedSubclass(TestSqlObject.java:321)

**Comment by qualidafial** [comment]
Oops, yeah I forgot to move sql files when I renamed that test DAO. Will fix when I get back to my computer.
