### PR TITLE
fix #1572: backport EmptyHandling

### LINKED ISSUE #1572: Do not throw an IllegalArgumentException when calling SqlStatement.bindList with an empty list
I have a query such as this:

```
    public List<String> load(List<String> namesToFind) {
        return db.withHandle(h -> h.createQuery("SELECT id FROM users WHERE name IN (<namesToFind>)")
                .bind("namesToFind", namesToFind)
                .mapTo(String.class))
                .list();
    }
```

Currently, when I call this method when the `namesToFind` parameter is an empty list, I get the following exception:

```
java.lang.IllegalArgumentException: Query.bindList was called with an empty list.
	at org.jdbi.v3.core.statement.SqlStatement.bindList(SqlStatement.java:1299) ~[jdbi3-core-3.6.0.jar:?]
```

I understand that it is part of the API specification that `bindList` and related methods throw this exception. However, when using the `BindList` annotation, there is an `onEmpty` attribute which allows the user to change the behaviour when the input list is null. Would it be possible to add a similar `onEmpty` configuration for the fluent API? I am not really experienced enough with JDBI to be able to suggest a solution so I'd be happy to hear suggestions.

*Affects JDBI-core 3.9.0*

### PR DESCRIPTION
**Pull request by TheRealMarnes**
Implemented the EmptyHandling enum in core, leaving out the deprecated value and redesigning the new API to accept an interface (making the enum a convenience, not a restriction).

### CODE REVIEW

File: core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java [hunk 1]
```diff
@@ -1250,20 +1263,34 @@ public final This bindBySqlType(int position, Object value, int sqlType) {
...
+     * @param values  vararg values that will be comma-spliced into the defined attribute value.
      * @return this
      * @throws IllegalArgumentException if the vararg array is empty.
+     * @see BindListEmptyHandling
      */
-    public final This bindList(String key, Object... values) {
-        if (values.length == 0) {
-            throw new IllegalArgumentException(
-                    getClass().getSimpleName() + ".bindList was called with no vararg values.");
+    public final This bindList(String key, BiConsumer<SqlStatement, String> onEmpty, Object... values) {
```
Comment (TheRealMarnes) [inline core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java]: the odds of someone legit passing a `BiConsumer<SqlStatement, String>` as a vararg value to be bound as a query param, which would cause this method to falsely match and break their query, are ridiculous...

Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java]: Would it be better to move `onEmpty` to the first argument?  That both avoids this caveat (even though I agree it'd be a ridiculous situation) and it also avoids splitting `key` from `values` which are the "most related" arguments.

File: core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+ * limitations under the License.
+ */
+package org.jdbi.v3.core.statement;
+
+import java.util.function.BiConsumer;
+
+/**
+ * describes what should be done if the value passed to {@link SqlStatement#bindList} is null or empty
+ */
+public enum BindListEmptyHandling implements BiConsumer<SqlStatement, String> {
```
Comment (stevenschlansker) [inline core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java]: Should this really have `BindList` in the name?  What if we want to use it from another feature?  Seems like this might be overly specific.

File: core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+     * {@code select * from things where x in ()}
+     */
+    VOID {
+        @Override
+        public void accept(SqlStatement stmt, String key) {
+            stmt.define(key, "");
+        }
+    },
+    /**
+     * <p>Output "null" (without quotes, as keyword), useful e.g. in postgresql where "in ()" is invalid syntax.</p>
```
Comment (stevenschlansker) [inline core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java]: The usual way to indicate a keyword is `{@code null}`

File: core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java [hunk 4]
```diff
@@ -1284,15 +1311,17 @@ public final This bindList(String key, Object... values) {
...
      * @return this
      * @throws IllegalArgumentException if the list is empty.
+     * @see BindListEmptyHandling
      */
-    public final This bindList(String key, List<?> values) {
-        if (values.isEmpty()) {
-            throw new IllegalArgumentException(
-                    getClass().getSimpleName() + ".bindList was called with an empty list.");
+    public final This bindList(String key, BiConsumer<SqlStatement, String> onEmpty, List<?> values) {
+        if (values == null || values.isEmpty()) {
```
Comment (stevenschlansker) [inline core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java]: Hm, this is a sneaky change.  I guess that's fine to catch `null` here too.

File: core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java (hunk 1 above)
Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java]: Hmm why not

File: core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java (hunk 2 above)
Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java]: I named it so specifically so that it would be discoverable via IDE hints to people typing "bindlist", and because it really doesn't feel like something that can be reused for anything. But if you insist

File: core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java (hunk 3 above)
Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java]: The problem here is the perspective to document from: do we document from the perspective of what we are binding, or from what we will output in the query? Both are familiar to users and neither seems like the less important one to me, though if I absolutely had to choose I guess I would choose the query POV.

File: core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java (hunk 4 above)
Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java]: Yeah I figured this would be ok to change since nobody is eager for NPEs from libraries

File: core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java (hunk 2 above)
Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java]: I don't insist.  Just a comment.  I don't have a strong preference.

File: core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java (hunk 3 above)
Comment (stevenschlansker) [reply core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java]: I just think it's strange to put a quotation mark and then immediately undo it in a parenthetical, when there's an out-of-the-box style for `keyword`.  I don't feel too strongly about it either way.

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/statement/BindListEmptyHandling.java]: Yeah but that's not the issue... We _define_ a _string_ `"null"`, which _renders_ to the _keyword_ `null`. It does both. The question is which POV do we document from? If I had to guess I'd document the query content since that's what people will mostly need to think about.

File: core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java [hunk 5]
```diff
@@ -1284,15 +1311,17 @@ public final This bindList(String key, Object... values) {
...
+     * @param values  list of values that will be comma-spliced into the defined attribute value.
      * @return this
      * @throws IllegalArgumentException if the list is empty.
+     * @see EmptyHandling
      */
-    public final This bindList(String key, List<?> values) {
-        if (values.isEmpty()) {
-            throw new IllegalArgumentException(
-                    getClass().getSimpleName() + ".bindList was called with an empty list.");
+    public final This bindList(String key, BiConsumer<SqlStatement, String> onEmpty, List<?> values) {
```
Comment (TheRealMarnes) [inline core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java]: should I actually maybe declare this as `Iterable` and add an overload for `Iterator` so that it aligns with `@BindList`?

Comment (TheRealMarnes) [reply core/src/main/java/org/jdbi/v3/core/statement/SqlStatement.java]: also, parameter order is not correct yet

**Comment by TheRealMarnes** [comment]
Commits rebased and overloads for `Iterable` and `Iterator` added for similar flexibility to `@BindList`
