### PR TITLE
JdbiPlugin throws SqlException

### LINKED ISSUE #1440: Allow JdbiPlugin::customizeConnection to throw SQLException
For implementors of `JdbiPlugin::customizeConnection` that call methods on the given `Connection` it would be convenient to just pass through `SQLException`s.

For example, instead of 
```java
    jdbi.installPlugin(new JdbiPlugin() {
      @Override
      public Connection customizeConnection(Connection conn) {
        try {
          conn.setHoldability(HOLD_CURSORS_OVER_COMMIT);
        } catch (SQLException exception) {
          throw new RuntimeException(exception);
        }
        return conn;
      }
    });
```
clients could write 
```java
    jdbi.installPlugin(new JdbiPlugin() {
      @Override
      public Connection customizeConnection(Connection conn) {
        conn.setHoldability(HOLD_CURSORS_OVER_COMMIT);
        return conn;
      }
    });
```
And spare the boilerplate catch-and-rethrow code. Furthermore, exception handling would be consistent for all `SQLException`s.

### PR DESCRIPTION
**Pull request by stevenschlansker**
Fixes #1440 
This is a small source breaking change.  It should not be a binary incompatible change -- checked exceptions are compiler fiction -- but if anyone calls `JdbiPlugin` methods themselves (why would they??) they may now have to handle it.

### CODE REVIEW

File: core/src/main/java/org/jdbi/v3/core/Jdbi.java [hunk 1]
```diff
@@ -224,7 +225,7 @@ public Jdbi installPlugins() {
      * @return this
      */
     public Jdbi installPlugin(JdbiPlugin plugin) {
-        plugin.customizeJdbi(this);
+        Unchecked.runnable(() -> plugin.customizeJdbi(this)).run();
```
Comment (TheRealMarnes) [inline core/src/main/java/org/jdbi/v3/core/Jdbi.java]: `Unchecked.consumer(plugin::customizeJdbi).accept(this);` is the right mantra :)

File: core/src/main/java/org/jdbi/v3/core/internal/exceptions/CheckedRunnable.java [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package org.jdbi.v3.core.internal.exceptions;
+
+@FunctionalInterface
+public interface CheckedRunnable {
+    void run() throws Exception;
+}
```
Comment (TheRealMarnes) [inline core/src/main/java/org/jdbi/v3/core/internal/exceptions/CheckedRunnable.java]: missing newline, checkstyle failure

**Comment by TheRealMarnes** [comment]
@stevenschlansker I'll leave merging to you or @qualidafial since I added a commit.
