### PR TITLE
Package by feature

### LINKED ISSUE #582: Package by feature
Audit our existing APIs before we go to beta, and move classes around to follow a [package-by-feature](http://www.javapractices.com/topic/TopicAction.do?Id=205) approach.

Move into packages (audit in progress):

Core:
* [x] org.jdbi.v3.core
  * [x] JdbiException
  * [x] ConnectionException (previously UnableToObtainConnectionException)
  * [x] CloseException (previously UnableToCloseResourceException)
* [x] org.jdbi.v3.core.argument
  * [x] BeanPropertyArguments, MapArguments
* [x] org.jdbi.v3.core.config
  * [x] ConfigRegistry, JdbiConfig, Configurable
* [x] org.jdbi.v3.core.generics
  * [x] GenericTypes, GenericType
* [x] org.jdbi.v3.core.mapper
  * [x] MappingException (carved out from UnableToCreateStatementException usages)
  * [x] NoSuchMapperException (previously NoSuchColumnMapperException)
* [x] org.jdbi.v3.core.result
  * [x] GeneratedKeys, EmptyResultIterator
  * [x] ResultBearing, ResultSetAccumulator, StreamCallback, StreamConsumer, ResultIterator, ResultSetResultIterator, RowView
  * [x] ResultSetIterable, ResultSetCallback
  * [x] NoResultsException, ResultSetException, UnableToProduceResultException
* [x] org.jdbi.v3.core.statement
  * [x] BaseStatement, StatementContext, TimingCollector, (StatementExecutor -> ResultProducer) _Edit: maybe ResultProducer would be better in `result` package?)_
  * [x] Batch, PreparedBatch, PreparedBatchPart
  * [x] Call, CallableStatementMapper, OutParameters
  * [x] SqlStatement, Binding, Cleanable, Cleanables, StatementBuilder, DefaultStatementBuilder, DefaultStatementBuilderFactory
  * [x] Query
  * [x] Script
  * [x] StatementException, UnableToCreateStatementException, UnableToExecuteStatementException
* [x] org.jdbi.v3.core.transaction
  * [x] TransactionException, UnableToManipulateTransactionIsolationLevelException, UnableToRestoreAutoCommitStateException
* [x] Move exception classes by feature?
* [x] Unit tests too
  
Sql Object:
* [x] org.jdbi.v3.sqlobject.config
  * [x] ConfigurerFactory, ConfiguringAnnotation, OverrideStatementRewriterWith, RegisterArgumentFactory, RegisterBeanMapper, RegisterCollectorFactory, RegisterColumnMapper, RegisterColumnMapperFactory, RegisterConstructorMapper, RegisterFieldMapper, RegisterJoinRowMapper, RegisterObjectArgumentFactory, RegisterRowMapper, RegisterRowMapperFactory
* [x] org.jdbi.v3.sqlobject.customizers
  * [x] Bind, BindBean, BindMap, SqlStatementCustomizer, SqlStatementCustomizerFactory, SqlStatementCustomizingAnnotation
* [x] org.jdbi.v3.sqlobject.statement
  * [x] CustomizingStatementHandler, ResultReturner, SqlBatch, SqlCall, SqlQuery, SqlUpdate, BatchChunkSize
* [x] org.jdbi.v3.sqlobject.transaction
  * [x] Transaction, Transactional, TransactionalCallback, TransactionalConsumer, TransactionIsolation
* [x] Depluralize package names (e.g. `customizers` -> `customizer`)
* ~Unit tests package by feature~ moving to a follow-up issue

Other miscellaneous cleanup:
* [x] Make annotation-specific classes inner types of their annotations.
  * [x] BatchHandler, CallHandler, DefaultGeneratedKeyMapper, QueryHandler, UpdateHandler
* [x] Inline handlers/decorators as lambdas inside their factories.
  * [x] CreateSqlObjectHandler, TransactionDecorator
* ~Make Transactional methods default, and extend GetHandle instead of mixins?~ handling separately in #607
  * ~BeginHandler, CommitHandler, InTransactionHandler, InTransactionWithIsolationLevelHandler, ReleaseSavepointHandler, RollbackHandler, RollbackSavepointHandler, SavepointHandler~
  * ~Or maybe add a meta-annotation e.g. `@Mixin(Transactional.Factory.class)`, so users can provide their own mixins?~
* [x] SqlAnnotations.getAnnotationValue wants to be in the internal package
* [x] UnableToCreateSqlObjectException: move to wherever `@CreateSqlObject` ends up?

Odd one-off annotations that are hard to place:
* ~BatchChunkSize (used exclusively by batch, but doesn't seem to belong in statement~ (statement package)
* ~CreateSqlObject (SQL method annotation)~ (leave in sqlobject)
* ~DecoratorOrder~ (leave in sqlobject)
* ~GetGeneratedKeys (used by `@SqlBatch` and `@SqlUpdate`)~ (leave in sqlobject)
* ~SingleValue (used by `@SqlBatch`, `@SqlQuery`, and probably in cases of `@SqlUpdate @GetGeneratedKeys`)~ (leave in sqlobject)
* ~UseRowMapper (used exclusively by `@SqlQuery`)~ (leave in customizer)

### PR DESCRIPTION
**Pull request by qualidafial**
Fixes #582. See that issue description for a detailed list of changes in this PR.

Only core and sqlobject were touched in any meaningful way.

I had to make a couple things public in order to allow cross-package access. After submitting the PR I'll annotate some of them directly if they require explanation.

The diff will tell you some things, but really the most important review is to check out this branch on your machine and browse the project packages, and see where things live after this PR.

Please call out any classes that you believe should go elsewhere.

@arteam @stevenschlansker This is ready for review.

### CODE REVIEW

File: core/src/main/java/org/jdbi/v3/core/Cleanables.java [hunk 1]
```diff
@@ -1,107 +0,0 @@
...
-import org.jdbi.v3.core.statement.StatementBuilder;
-import org.jdbi.v3.core.transaction.TransactionState;
-
-/**
- * Resource management for JDBI. Cleanables can be registered on a SQL statement and they get cleaned up when the
- * statement finishes or (in the case of a ResultIterator), the object representing the results is closed.
- *
- * Resources managed by JDBI are {@link ResultSet}, {@link Statement}, {@link Handle} and {@link StatementBuilder} for historical reasons.
- */
-class Cleanables implements Closeable
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/Cleanables.java]: All the methods in this class were inlined. `StatementContext` now owns the `Set<Cleanable>`

File: core/src/main/java/org/jdbi/v3/core/CloseException.java [hunk 2]
```diff
@@ -11,13 +11,16 @@
...
-public class UnableToCloseResourceException extends JdbiException
+/**
+ * Thrown when an exception occurs while attempting to close a database resource.
+ */
+public class CloseException extends JdbiException
 {
     private static final long serialVersionUID = 1L;
 
-    public UnableToCloseResourceException(String string, Throwable throwable)
+    public CloseException(String string, Throwable throwable)
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/CloseException.java]: This was something I wanted to try: shortening our exception names. If we made them more broad we could reuse the same exceptions for some things, and then the names don't have to be verbose--just the exception message.

File: core/src/main/java/org/jdbi/v3/core/Handle.java [hunk 3]
```diff
@@ -85,6 +91,10 @@ public Connection getConnection() {
         return this.connection;
     }
 
+    public StatementBuilder getStatementBuilder() {
+        return statementBuilder;
+    }
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/Handle.java]: Previously, Handle had access to the constructors of Batch, Call, PreparedBatch, Query, and Update.

Since those classes are now in the `statement` package, I added a public static factory method to each, that accepts this Handle as a parameter. Making the statement builder public allowed each factory method to only need a Handle and sql parameter.

File: core/src/main/java/org/jdbi/v3/core/OnDemandExtensions.java [hunk 4]
```diff
@@ -18,7 +18,7 @@
 import java.lang.reflect.Method;
 import java.lang.reflect.Proxy;
 
-public class OnDemandExtensions {
+class OnDemandExtensions {
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/OnDemandExtensions.java]: This was never intended to be public--glad I caught this

File: core/src/main/java/org/jdbi/v3/core/argument/BeanPropertyArguments.java [hunk 5]
```diff
@@ -21,18 +21,17 @@
...
 import java.util.Optional;
 
-import org.jdbi.v3.core.argument.Argument;
-import org.jdbi.v3.core.argument.NamedArgumentFinder;
-import org.jdbi.v3.core.exception.UnableToCreateStatementException;
+import org.jdbi.v3.core.statement.StatementContext;
+import org.jdbi.v3.core.statement.UnableToCreateStatementException;
 
-class BeanPropertyArguments implements NamedArgumentFinder
+public class BeanPropertyArguments implements NamedArgumentFinder
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/argument/BeanPropertyArguments.java]: This logically belongs in the argument package, but I don't like exposing the constructor. Maybe a static factory method instead?

File: core/src/main/java/org/jdbi/v3/core/argument/MapArguments.java [hunk 6]
```diff
@@ -11,24 +11,23 @@
...
  * Binds all entries of a map as arguments.
  */
-class MapArguments implements NamedArgumentFinder
+public class MapArguments implements NamedArgumentFinder
 {
     private final Map<String, ?> args;
     private final StatementContext ctx;
 
-    MapArguments(Map<String, ?> args, StatementContext ctx)
+    public MapArguments(Map<String, ?> args, StatementContext ctx)
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/argument/MapArguments.java]: Ditto my comment in BeanPropertyArguments

File: core/src/main/java/org/jdbi/v3/core/generic/GenericType.java [hunk 7]
```diff
@@ -11,17 +11,15 @@
...
+package org.jdbi.v3.core.generic;
 
 import java.lang.reflect.Type;
 
 public abstract class GenericType<T> {
     private final Type type;
 
     protected GenericType() {
-        this.type = findGenericParameter(getClass(), GenericType.class)
+        this.type = GenericTypes.findGenericParameter(getClass(), GenericType.class)
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/generic/GenericType.java]: Ugh, IntelliJ un-imported these static methods all over the place.

File: core/src/main/java/org/jdbi/v3/core/mapper/NoSuchMapperException.java [hunk 8]
```diff
@@ -11,24 +11,21 @@
...
 
-public class TransactionFailedException extends JdbiException
-{
-    private static final long serialVersionUID = 1L;
+import org.jdbi.v3.core.JdbiException;
 
-    public TransactionFailedException(String string, Throwable throwable)
-    {
+@SuppressWarnings("serial")
+public class NoSuchMapperException extends JdbiException {
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/mapper/NoSuchMapperException.java]: lol at this rename detection.

File: core/src/main/java/org/jdbi/v3/core/statement/Batch.java [hunk 9]
```diff
@@ -31,15 +29,23 @@
  */
 public class Batch extends BaseStatement<Batch>
 {
+    public static Batch create(Handle handle) {
+        ConfigRegistry config = handle.getConfig().createCopy();
+        return new Batch(config,
+                handle.getConnection(),
+                handle.getStatementBuilder(),
+                new StatementContext(config, handle.getExtensionMethod()));
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/statement/Batch.java]: Batch, Call, Query, and Config have really similar implementations for this factory method.

I wonder if we could push all this repetitive code into the BaseStatement constructor.

File: core/src/main/java/org/jdbi/v3/core/statement/StatementContext.java [hunk 10]
```diff
@@ -298,27 +310,50 @@ public Binding getBinding()
...
-    {
-        return cleanables;
-    }
-
+    /**
+     * Registers a {@code Cleanable} to be invoked when the statement context is closed. Cleanables can be registered
+     * on a statement context, which will be cleaned up when
+     * the statement finishes or (in the case of a ResultIterator), the object representing the results is closed.
+     * <p>
+     * Resources cleaned up by JDBI include {@link ResultSet}, {@link Statement}, {@link Handle}.
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/statement/StatementContext.java]: oops, period should be comma

File: core/src/main/java/org/jdbi/v3/core/statement/StatementContext.java [hunk 11]
```diff
@@ -370,7 +405,7 @@ public boolean isConcurrentUpdatable() {
      *
      * @param concurrentUpdatable if the result set should be concurrent updatable.
      */
-    void setConcurrentUpdatable(final boolean concurrentUpdatable) {
+    public void setConcurrentUpdatable(final boolean concurrentUpdatable) {
```
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/statement/StatementContext.java]: These had to be made public to be accessible across core / statement packages. I don't think this configuration for the statement builder really belongs here in `StatementContext`. I wonder if it could live on the StatementBuilder.

File: core/src/test/java/org/jdbi/v3/core/result/TestIterator.java [hunk 12]
```diff
@@ -51,13 +55,13 @@ public void testSimple() throws Exception {
             .mapToMap()
             .iterator();
 
-        assertThat(it.hasNext()).isTrue();
+        Assertions.assertThat(it.hasNext()).isTrue();
```
Comment (qualidafial) [inline core/src/test/java/org/jdbi/v3/core/result/TestIterator.java]: oh goddammit intellij

File: jpa/src/main/java/org/jdbi/v3/jpa/JpaMapper.java [hunk 13]
```diff
@@ -60,7 +61,7 @@ private C tryMap(ResultSet rs, StatementContext ctx)
             if (member != null) {
                 Type memberType = member.getType();
                 ColumnMapper<?> columnMapper = ctx.findColumnMapperFor(memberType)
-                        .orElseThrow(() -> new NoSuchColumnMapperException("No column mapper for " + memberType));
+                        .orElseThrow(() -> new NoSuchMapperException("No column mapper for " + memberType));
```
Comment (qualidafial) [inline jpa/src/main/java/org/jdbi/v3/jpa/JpaMapper.java]: Off topic, but we should specialize this mapper

File: sqlobject/src/main/java/org/jdbi/v3/sqlobject/BatchHandler.java [hunk 14]
```diff
@@ -1,279 +0,0 @@
...
-import org.jdbi.v3.core.ResultIterable;
-import org.jdbi.v3.core.ResultIterator;
-import org.jdbi.v3.core.StatementContext;
-import org.jdbi.v3.core.exception.UnableToCreateStatementException;
-import org.jdbi.v3.core.mapper.RowMapper;
-import org.jdbi.v3.core.util.ReflectionArrayIterator;
-import org.jdbi.v3.sqlobject.customizers.BatchChunkSize;
-import org.jdbi.v3.sqlobject.exceptions.UnableToCreateSqlObjectException;
-
-class BatchHandler extends CustomizingStatementHandler
```
Comment (qualidafial) [inline sqlobject/src/main/java/org/jdbi/v3/sqlobject/BatchHandler.java]: Moved these `@Sql*` handlers inner classes of their annotations

File: sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestOnDemandSqlObject.java [hunk 15]
```diff
@@ -194,7 +196,7 @@ public void testSqlFromExternalFileWorks() throws Exception
         List<Something> findAll();
     }
 
-    static class CrashingMapper implements RowMapper<Something>
+    public static class CrashingMapper implements RowMapper<Something>
```
Comment (qualidafial) [inline sqlobject/src/test/java/org/jdbi/v3/sqlobject/TestOnDemandSqlObject.java]: public for cross-package access to constructor

File: jpa/src/main/java/org/jdbi/v3/jpa/JpaMapper.java (hunk 13 above)
Comment (qualidafial) [inline jpa/src/main/java/org/jdbi/v3/jpa/JpaMapper.java]: Opened #625

File: core/src/main/java/org/jdbi/v3/core/statement/StatementContext.java (hunk 11 above)
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/statement/StatementContext.java]: Opened #626

File: core/src/main/java/org/jdbi/v3/core/Handle.java [hunk 16]
```diff
@@ -199,11 +209,7 @@ public int update(String sql, Object... args) {
      * @see Handle#prepareBatch(String)
      */
     public Batch createBatch() {
-        ConfigRegistry batchConfig = getConfig().createCopy();
-        return new Batch(batchConfig,
-                         this.connection,
-                         statementBuilder,
-                         new StatementContext(batchConfig, extensionMethod.get()));
+        return Batch.create(this);
```
Comment (stevenschlansker) [inline core/src/main/java/org/jdbi/v3/core/Handle.java]: Nice

File: core/src/main/java/org/jdbi/v3/core/mapper/NoSuchMapperException.java (hunk 8 above)
Comment (stevenschlansker) [inline core/src/main/java/org/jdbi/v3/core/mapper/NoSuchMapperException.java]: Exceptional

File: core/src/test/java/org/jdbi/v3/core/internal/ReflectionArrayIteratorTest.java [hunk 17]
```diff
@@ -11,35 +11,31 @@
...
+    public void testIntArray() {
         final Iterator<Object> it = new ReflectionArrayIterator(new int[]{1, 2, 3});
 
         assertThat(it).containsExactly(1, 2, 3);
     }
 
     @Test
-    public void testEmptyArray()
-    {
+    public void testEmptyArray() {
```
Comment (stevenschlansker) [inline core/src/test/java/org/jdbi/v3/core/internal/ReflectionArrayIteratorTest.java]: Sneaky ;)

Comment (qualidafial) [inline core/src/test/java/org/jdbi/v3/core/internal/ReflectionArrayIteratorTest.java]: heh, I think I code formatted the entire class a few times when I was only targeting a few lines.

File: core/src/main/java/org/jdbi/v3/core/statement/Batch.java (hunk 9 above)
Comment (qualidafial) [inline core/src/main/java/org/jdbi/v3/core/statement/Batch.java]: Opened #628

**Comment by qualidafial** [comment]
@arteam I merged this so @stevenschlansker can rebase his mixin PR sooner. If you find any issues with this PR, leave a review and we'll follow up in a separate PR.
