### PR TITLE
Sqlite support for Jdbi

### LINKED ISSUE #994: Exception thrown when binding argument of supported type.
I'm trying to insert a bean into an sqlite database. The bean has a url field of type URL. When I try inserting it into the database i get this error:

````java
Exception in thread "main" org.jdbi.v3.core.statement.UnableToCreateStatementException: Exception while binding named parameter 'url' [statement:"INSERT INTO book (title, url) VALUES (:title, :url);", rewritten:"INSERT INTO book (title, url) VALUES (:title, :url);", parsed:"ParsedSql{sql='INSERT INTO book (title, url) VALUES (?, ?);', parameters=ParsedParameters{positional=false, parameterNames=[title, url]}}", arguments:{ positional:{}, named:{}, finder:[{lazy bean property arguments "jdbc.Book@5f3a4b84"]}]
	at org.jdbi.v3.core.statement.ArgumentBinder.bindNamed(ArgumentBinder.java:63)
	at org.jdbi.v3.core.statement.ArgumentBinder.bind(ArgumentBinder.java:27)
	at org.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1443)
	at org.jdbi.v3.core.result.ResultProducers.lambda$returningUpdateCount$0(ResultProducers.java:39)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:53)
	at org.jdbi.v3.core.statement.Update.execute(Update.java:41)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$new$2(SqlUpdateHandler.java:56)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.lambda$configureReturner$3(SqlUpdateHandler.java:69)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:155)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.invoke(SqlUpdateHandler.java:29)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:162)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:73)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:161)
	at com.sun.proxy.$Proxy4.addBook(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$0(OnDemandExtensions.java:60)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:464)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$create$1(OnDemandExtensions.java:57)
	at com.sun.proxy.$Proxy4.addBook(Unknown Source)
````
Here are my dao interface and bean class

````java
public interface BookDao {
    @SqlUpdate("CREATE TABLE IF NOT EXISTS book (" +
            "id INTEGER PRIMARY KEY, " +
            "title TEXT, " +
            "url TEXT);")
    void createTableIfNotExits();

    @SqlQuery("SELECT * FROM book;")
    @RegisterConstructorMapper(Book.class)
    List<Book> getAllBooks();

    @SqlUpdate("INSERT INTO book (title, url) VALUES (:title, :url);")
    boolean addBook(@BindBean Book book);

    @SqlUpdate("DELETE FROM book WHERE id=:id;")
    boolean removeBooks(@BindBean Book book);
}
````

````java
public class Book {
    private final int id;
    private String title;
    private URL url;

    public Book(@ColumnName("id") int id, @ColumnName("title") String title, @ColumnName("url") URL url) {
        this.id = id;
        this.title = title;
        this.url = url;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public URL getUrl() {
        return url;
    }
}
````

According to the documentation, URL is a supported type so i'm thinking it would automatically be mapped to a string for me. Am I doing something wrong?

### PR DESCRIPTION
**Pull request by edwinnyawoli**
Added plugin to support using sqlite with jdbi. 
Fixes #994

### CODE REVIEW

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/URLArgumentFactory.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+import org.jdbi.v3.core.argument.ArgumentFactory;
+import org.jdbi.v3.core.config.ConfigRegistry;
+
+import java.net.URL;
+import java.sql.Types;
+
+/**
+ * Build URL objects as strings.
+ */
+public class URLArgumentFactory extends AbstractArgumentFactory<URL> {
```
Comment (qualidafial) [inline sqlite/src/main/java/org/jdbi/v3/sqlite3/URLArgumentFactory.java]: Let's make this and the mapper class package private so that the plugin is the only public API

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+public class URLColumnMapper implements ColumnMapper<URL> {
+
+    @Override
+    public URL map(ResultSet r, int columnNumber, StatementContext ctx) throws SQLException {
+        URL url = null;
+
+        try {
+            url = URI.create(r.getString(columnNumber)).toURL();
+        } catch (MalformedURLException e) {
+            e.printStackTrace();
```
Comment (qualidafial) [inline sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java]: I'm of two minds on this exception. On one hand it seems like the more correct approach is to raise the exception rather than swallow it. On the other hand, that means if a malformed URL somehow gets into the database, you could never read that row out again without an exception--lame.

Any any rate, this should be logged with SLF4J rather than printed to STDOUT

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+    }
+
+    @Test
+    public void testInsertUrlSuccessful() {
+        String goolgeString = "http://www.google.com";
+        URL googleUrl = null;
+        try {
+            googleUrl = URI.create(goolgeString).toURL();
+        } catch (MalformedURLException e) {
+            e.printStackTrace();
```
Comment (qualidafial) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Test method should just throw exception rather than swallowing an unexpected exception.

**Comment by qualidafial** [comment]
Can we also get a section in `index.adoc` about this new module?

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/SQLitePlugin.java [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+ */
+package org.jdbi.v3.sqlite3;
+
+import org.jdbi.v3.core.Jdbi;
+import org.jdbi.v3.core.spi.JdbiPlugin;
+
+import java.net.URL;
+
+/**
+ * Jdbc plugin for SQLite
```
Comment (stevenschlansker) [inline sqlite/src/main/java/org/jdbi/v3/sqlite3/SQLitePlugin.java]: This is a `jdbi` plugin :)
Also the javadoc is missing the required `.` termination.

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/URLArgumentFactory.java [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+    /**
+     * Constructs an {@link ArgumentFactory} for type {@code URL}.
+     */
+    public URLArgumentFactory() {
+        super(Types.VARCHAR);
+    }
+
+    @Override
+    protected Argument build(URL url, ConfigRegistry config) {
+        return (position, statement, ctx) -> statement.setString(position, url.toString());
```
Comment (stevenschlansker) [inline sqlite/src/main/java/org/jdbi/v3/sqlite3/URLArgumentFactory.java]: Should this handle a null url?

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java (hunk 2 above)
Comment (stevenschlansker) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java]: I think I'd rather it throw.  The data you requested from the database cannot be represented in the requested container type.  `null` is indistinguishable from a valid return of a different value, so that's no good.  So we must fail.

If your data may be a URL or maybe not, you should fetch it as a string and guard the conversion, IMO.  Or we could make this a configurable policy with choices of `THROW` vs `SWALLOW_RETURN_NULL`.  But I think the default has to be to throw the exception.

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+
+    Handle handle;
+
+    @Before
+    public void setUp() throws Exception {
+        Jdbi jdbi = Jdbi.create("jdbc:sqlite::memory:");
+        jdbi.installPlugin(new SQLitePlugin());
+        handle = jdbi.open();
+        handle.useTransaction(handle -> {
+            handle.execute("DROP TABLE IF EXISTS foo");
```
Comment (stevenschlansker) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: I don't think `foo` can ever exist here, right, since the above opens a unique in-memory db?

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+        String goolgeString = "http://www.google.com";
+        URL googleUrl = null;
+        try {
+            googleUrl = URI.create(goolgeString).toURL();
+        } catch (MalformedURLException e) {
+            e.printStackTrace();
+        }
+
+        handle.createUpdate("INSERT INTO foo VALUES (:url)")
+                .bind("url", googleUrl)
```
Comment (stevenschlansker) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Also test that e.g. `bindByType("url", null, URL.class)` works

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/URLArgumentFactory.java (hunk 5 above)
Comment (qualidafial) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/URLArgumentFactory.java]: `AbstractArgumentFactory` already handles nulls.

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java (hunk 2 above)
Comment (qualidafial) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java]: Yes, I think you're right. +1 to throw

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/SQLitePlugin.java (hunk 4 above)
Comment (edwinnyawoli) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/SQLitePlugin.java]: lol...the names got mixed up in my head.

Comment (qualidafial) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/SQLitePlugin.java]: I don't know why, they're totally different :trollface:

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java (hunk 6 above)
Comment (edwinnyawoli) [reply sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: yeah...you're right

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/SQLitePlugin.java (hunk 4 above)
Comment (edwinnyawoli) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/SQLitePlugin.java]: 😅

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+import java.sql.SQLException;
+
+class URLColumnMapper implements ColumnMapper<URL> {
+
+    @Override
+    public URL map(ResultSet r, int columnNumber, StatementContext ctx) throws SQLException {
+        URL url = null;
+
+        try {
+            url = URI.create(r.getString(columnNumber)).toURL();
```
Comment (arteam) [inline sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java]: We could just use `return`, because `MalformedURLException` is wrapped by another exception and we have only one point of return in the method.

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 9]
```diff
@@ -0,0 +1,61 @@
...
+public class TestUrls {
+
+    Handle handle;
+
+    @Before
+    public void setUp() throws Exception {
+        Jdbi jdbi = Jdbi.create("jdbc:sqlite::memory:");
+        jdbi.installPlugin(new SQLitePlugin());
+        handle = jdbi.open();
+        handle.useTransaction(handle -> {
```
Comment (arteam) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: We could use a more simple lambda-expression form without the curly braces:
```java
handle.useTransaction(h -> h.execute("CREATE TABLE foo(url URL);"))
```

Comment (arteam) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: We could use a more simple form of lambda-expressions without the curly braces:
```java
handle.useTransaction(h -> h.execute("CREATE TABLE foo(url URL);"))
```

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 10]
```diff
@@ -0,0 +1,61 @@
...
+import java.net.URI;
+import java.net.URL;
+
+public class TestUrls {
+
+    Handle handle;
+
+    @Before
+    public void setUp() throws Exception {
+        Jdbi jdbi = Jdbi.create("jdbc:sqlite::memory:");
```
Comment (arteam) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: I think it would be nice to add some random  suffix to the database name to avoid test clashes if we will have more SQLite tests in the future.

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 11]
```diff
@@ -0,0 +1,61 @@
...
+    @After
+    public void tearDown() throws Exception {
+        handle.close();
+    }
+
+    @Test
+    public void testInsertUrlSuccessful() throws MalformedURLException {
+        String goolgeString = "http://www.google.com";
+        URL googleUrl = null;
+        googleUrl = URI.create(goolgeString).toURL();
```
Comment (arteam) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: The `URL` class has a constructor which accepts `String`, so we can initialize it without `URI`:
```java
new URL("http://www.google.com")
```

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 12]
```diff
@@ -0,0 +1,61 @@
...
+
+        handle.createUpdate("INSERT INTO foo VALUES (:url)")
+                .bind("url", googleUrl)
+                .execute();
+
+        Assertions.assertThat(handle.createQuery("SELECT * FROM foo").mapTo(URL.class).findOnly()).isEqualTo(googleUrl);
```
Comment (arteam) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Just to be sure, I would avoid loading all columns from `foo` and specify the `url` column in `SELECT`

Comment (arteam) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Just FYI. this `equals` check actually makes a DNS request to resolve a Google's IP address and compare URLs by them. Relevant: http://brian.pontarelli.com/2006/12/05/mr-gosling-why-did-you-make-url-equals-suck/

Comment (stevenschlansker) [reply sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Great catch, maybe we should check `hasToString` instead?

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java (hunk 9 above)
Comment (stevenschlansker) [reply sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Single statements also are implicitly in a transaction, so it might be entirely redundant.

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java (hunk 12 above)
Comment (edwinnyawoli) [reply sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Thanks for the info.

Comment (edwinnyawoli) [reply sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: How come it hasn't been changed since? :thinking:

Comment (qualidafial) [reply sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Oh my god.

File: sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java (hunk 8 above)
Comment (edwinnyawoli) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java]: I'm not quite clear on what you're saying. Do you mean it should return the null in the catch block?

Comment (arteam) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java]: No, I meant you could just directly return `URI.create(r.getString(columnNumber)).toURL();` without declaring the `url` variable.

Comment (edwinnyawoli) [reply sqlite/src/main/java/org/jdbi/v3/sqlite3/URLColumnMapper.java]: Oh ok. I get it now

**Comment by qualidafial** [comment]
Looking over the comments, the remaining changes appear to be:

* Test with `bindByType()`
* Test mapping null URLs
* Use a random database name to avoid test conflicts

@edwinnyawoli Thanks very much--looking forward to merging this!

**Comment by edwinnyawoli** [comment]
I'll make the remaining changes and push soon. Thanks as well for the opportunity.

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java (hunk 10 above)
Comment (edwinnyawoli) [reply sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: Is it possible to specify a name for in memory databases?

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 13]
```diff
@@ -48,14 +46,14 @@ public void tearDown() throws Exception {
     @Test
     public void testInsertUrlSuccessful() throws MalformedURLException {
         String goolgeString = "http://www.google.com";
```
Comment (stevenschlansker) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: typo `goolge`

**Comment by edwinnyawoli** [comment]
Concerning the random database name, are you suggesting using a file with a random name vs the in memory database?

**Comment by arteam** [comment]
I think you can just append a random UUID to the memory database name; something like `"jdbc:sqlite::memory:" + UUID.randomUUID()`.

**Comment by edwinnyawoli** [comment]
An exception is thrown when creating the database with

````java
        Jdbi jdbi = Jdbi.create("jdbc:sqlite::memory:" + UUID.randomUUID().toString());
````

````java
    org.jdbi.v3.core.ConnectionException: java.sql.SQLException: opening db: ':memory:9f93fda2-466c-4a07-981e-f111d785eca9': The filename, directory name, or volume label syntax is incorrect

	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:321)
	at TestUrls.setUp(TestUrls.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.sql.SQLException: opening db: ':memory:9f93fda2-466c-4a07-981e-f111d785eca9': The filename, directory name, or volume label syntax is incorrect
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:203)
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
	at org.sqlite.JDBC.createConnection(JDBC.java:114)
	at org.sqlite.JDBC.connect(JDBC.java:88)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.jdbi.v3.core.Jdbi.lambda$create$0(Jdbi.java:103)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:305)
	... 24 more
````

**Comment by arteam** [comment]
It looks like the SQLite driver doesn't support several in-memory databases. Okay, let it slip, then.

File: sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java [hunk 14]
```diff
@@ -45,15 +46,36 @@ public void tearDown() throws Exception {
...
 
-        URL actualUrl = handle.createQuery("SELECT * FROM foo").mapTo(URL.class).findOnly();
+        URL actualUrl = handle.createQuery("SELECT url FROM foo").mapTo(URL.class).findOnly();
         Assertions.assertThat(actualUrl).hasToString(googleUrl.toString());
     }
 
+    @Test(expected = ResultSetException.class)
+    public void testMapNullUrlThrowsException() {
+        handle.createUpdate("INSERT INTO foo VALUES (:url)")
+                .bind("url", ((URL) null))
```
Comment (qualidafial) [inline sqlite/src/test/java/org/jdbi/v3/sqlite3/TestUrls.java]: The null case must be tested with `bindByType`. This case won't actually cause the URL argument to be used.

**Comment by qualidafial** [comment]
Thanks @edwinnyawoli for the PR!
